apiVersion: apps/v1
kind: Deployment
metadata:
  name: jenkins
  namespace: jenkins
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jenkins
  template:
    metadata:
      labels:
        app: jenkins
    spec:
      serviceAccountName: jenkins-sa
      containers:
      - name: jenkins
        image: jenkins-kubectl:latest
        ports:
        - containerPort: 8080
        securityContext:
          runAsUser: 0
          runAsGroup: 0
        volumeMounts:
        - name: jenkins-home
          mountPath: /var/jenkins_home
        lifecycle:
          postStart:
            exec:
              command:
              - /bin/bash
              - -c
              - |
                apt-get update -y && \
                apt-get install -y curl git apt-transport-https gnupg && \
                curl -fsSLo /usr/share/keyrings/kubernetes-archive-keyring.gpg https://packages.cloud.google.com/apt/doc/apt-key.gpg && \
                echo "deb [signed-by=/usr/share/keyrings/kubernetes-archive-keyring.gpg] https://apt.kubernetes.io/ kubernetes-xenial main" > /etc/apt/sources.list.d/kubernetes.list && \
                apt-get update -y && apt-get install -y kubectl
      volumes:
      - name: jenkins-home
        persistentVolumeClaim:
          claimName: jenkins-pvc
